OpenVicProject/OpenVic

- docs/project-file-structure.md
This adds a document describing how to organize the Godot project.
This document is meant as an initial draft put in place to help curtail the initial mess that can quickly occur within new projects. This document will need to be edited in the future as aspects of the project change, are added, or removed.
Includes:
* Root and User directory distinctions
* Where Mods are read from
* Godot Scene organization
* Godot Script organization
* Godot resources organization
Does not include:
* Anything related to C++
* Godot File naming convention
* Anything related to Asset file organization
* Anything related to the use of loaded data files i.e. the root/common/ directory mentioned in the requirements
* Mod file organization
> Project File Structure

- README.md
> Update to Godot 4 Release Candidate 4

- README.md
> Update to Godot 4 Release Candidate 5

- game/src/Autoload/Events/Options.gd
- game/src/Autoload/Resolution.gd
- game/src/LocaleButton.gd
- game/src/OptionMenu/MonitorDisplaySelector.gd
- game/src/OptionMenu/OptionsMenu.gd
- game/src/OptionMenu/ResolutionSelector.gd
- game/src/OptionMenu/ScreenModeSelector.gd
- game/src/OptionMenu/SettingNodes/SettingHSlider.gd
- game/src/OptionMenu/SettingNodes/SettingOptionButton.gd
- game/src/OptionMenu/VideoTab.tscn
- game/src/OptionMenu/VolumeGrid.gd
- Settings input sanatization for Locale, Resolution, Screen Mode, Monitor, Audio sliders.
- Revamped Resolution handling system to better handle custom resolutions.
- Various debug and release checks to avoid unexplained crashes.
> Add Setting Sanatization

- .gitignore
- game/common/credits.csv
- game/common/credits.csv.import
- game/src/Credits/Credits.gd
- game/src/Credits/Credits.tscn
- game/src/Credits/PersonLabelSettings.tres
- game/src/Credits/ProjectLabelSettings.tres
- game/src/Credits/RoleLabelSettings.tres
- game/src/GameMenu.gd
- game/src/GameMenu.tscn
- game/src/MainMenu/MainMenu.gd
- game/src/MainMenu/MainMenu.tscn
Added a data based Credits system that will search for a credits.csv file found within res://common/ and then render the credits according to the csv file.
The csv file format is:
title,project-title
role-name,person-name
role-name,person-name
...
Roles will be capitalized in application so can be lowercase.
The only needed row in the file for it to be accepted is title,project-title. All other rows are dynamically read and added.
Any additional data included in a row will not be read so it will not throw an error 
Requirements met by this PR:
* SS-17
* SS-29 [1]
* UI-32
* UI-34
* UIFUN-36
* UI-35
* UI-38
* UIFUN-37
* FS-4
Footnotes:
[1]: This requirement is sort of satisfied. It is technically possible for the system to render additional credit files, it does not have any functionality …
> Add Credits System

- game/common/credits.csv
- game/src/Credits/Credits.gd
- checks to avoid crashes on missing or incorrectly formatted credits files.
- alphabetic sorting of people within roles.
> Credits loading sanatization

- game/default_theme.tres
- game/src/Credits/Credits.gd
- game/src/Credits/Credits.tscn
- game/src/Credits/PersonLabelSettings.tres
- game/src/Credits/ProjectLabelSettings.tres
- game/src/Credits/RoleLabelSettings.tres
- game/src/GameMenu.tscn
Remove LabelSettings resources from Credits
Moved theme load from MainMenu to GameMenu scene
Removed Button references from default_theme resource
This enables reliable theme application
> Fix Credits to use theme type variants over LabelSettings

- docs/simulation/goods.md
- docs/simulation/ideologies.md
- docs/simulation/sim_doc_format.md
add: ideology documentation
add: goods documentation
add: sim doc format
I've added some data modelling to the documentation. This only covers partially covers the ideology and goods for now, but its a base that allows us to start actually keeping track of these things.
Couple notes:
This doesn't reference the Requirements in anyway and there are some pieces of data in here that I don't think are in reqs. This should probably be amended sometime in the future
> Added Data modelling Documentation - JC and Vanilla

- game/src/CreditsMenu/CreditsMenu.gd
- game/src/CreditsMenu/CreditsMenu.tscn
- game/src/GameMenu.gd
- game/src/GameMenu.tscn
For consistency with the rest of the menus and with the requirements.
> Refactor Credits -> CreditsMenu

- game/common/credits.csv.import
- game/export_presets.cfg
Fix MacOS OpenVic2.dmg export_path to OpenVic2.app
Rename macOS export preset to MacOS
Add `common/*` to include_filter
Make credits.csv not translation file but to keep the file on import
> Fix Export Issues

- .github/workflows/builds.yml
- game/common/credits.csv.import
- game/export_presets.cfg
Relies on #74 
Add push artifacts and release asset uploading
Add release integration
Add pck debug check and artifact
Update CI workflow with release archives
Update CI workflow for all pushes
Remove initial compile of godot-cpp from workflow
> Add extensive continuous integration and artifacts 

- .github/actions/openvic2-env/action.yml
- .github/workflows/builds.yml
- game/addons/openvic2-plugin/ReleaseExportEditorPlugin.gd
- game/addons/openvic2-plugin/openvic2-plugin.gd
- game/addons/openvic2-plugin/plugin.cfg
- game/project.godot
- game/src/GameMenu.tscn
- game/src/MainMenu/MainMenu.gd
- game/src/MainMenu/MainMenu.tscn
- game/src/MainMenu/ReleaseInfoBox.gd
- game/src/MainMenu/ReleaseInfoBox.tscn
- game/src/Utility/GIT_INFO.gd
- game/theme/main_menu.tres
Add commit hash label to MainMenu
Add click-copyable tag, commit hash, and checksum to main menu Rename VersionChecksumBox to ReleaseInfoBox
Move ReleaseInfoBox to separate scene and script
Add GIT_INFO.gd for generic project running
Add openvic2-plugin addon for handling export plugin
> Add automated Git release info retrieval on export

- game/src/GameSession/GameSession.tscn
- game/src/GameSession/GameSpeedPanel.gd
- game/src/GameSession/GameSpeedPanel.tscn
- game/src/LobbyMenu/LobbyMenu.gd
- game/src/LobbyMenu/LobbyMenu.tscn
- game/src/MusicConductor/MusicPlayer.gd
Implements following requirements:
**UI-74 UI-75 UI-76 UI-77**
Adds the following:
- Date + game speed panel
- Music player control to the game session
- Ability to quickly start from lobby by double-clicking a bookmark
> Minor map UI

- extension/src/GameSingleton.cpp
- extension/src/GameSingleton.hpp
- extension/src/openvic2/GameAdvancementHook.cpp
- extension/src/openvic2/GameAdvancementHook.hpp
- extension/src/openvic2/GameManager.cpp
- extension/src/openvic2/GameManager.hpp
- extension/src/openvic2/Logger.cpp
- extension/src/openvic2/Logger.hpp
- extension/src/openvic2/Types.hpp
- extension/src/openvic2/map/Building.cpp
- extension/src/openvic2/map/Building.hpp
- extension/src/openvic2/map/Map.cpp
- extension/src/openvic2/map/Map.hpp
- extension/src/openvic2/map/Province.cpp
- extension/src/openvic2/map/Province.hpp
- extension/src/openvic2/map/Region.hpp
- game/localisation/en_GB/menus.csv
- game/src/Autoload/Events.gd
- game/src/GameSession/GameSession.gd
- game/src/GameSession/GameSessionMenu.gd
- game/src/GameSession/GameSpeedPanel.gd
- game/src/GameSession/MapView.gd
- game/src/GameSession/ProvinceOverviewPanel.gd
- game/src/GameSession/ProvinceOverviewPanel.tscn
- game/src/GameSession/TerrainMap.gdshader
Requirements implemented in #94
- MAP-71, MAP-74, MAP-77
- MAP-11, MAP-72, MAP-73
- MAP-12, MAP-75, MAP-76
- MAP-13, MAP-78, MAP-79
- UI-183, UI-185, UI-186, UI-765, UI-187, UI-188, UI-189
- UI-191, UI-193, UI-194, UI-766, UI-195, UI-196, UI-197
- UI-199, UI-201, UI-202, UI-767, UI-203, UI-204, UI-205
Requirements implemented in this PR
- UI-62
> Req comments + cleanup + c++ registry refactoring

- game/project.godot
- game/src/ArgumentOption.gd
- game/src/ArgumentParser.gd
- game/src/ArgumentParser.tscn
- game/src/GameStart.tscn
Streamlines parsing of commandline arguments
Arguments reside in ProjectSettings as `openvic2/data/arguments` as a dictionary
The dictionary's key is the option name
The dictionary is set with default values
This enables project setting overrides for arguments (user specified arguments take priority)
Add help commandline option
Prepare for removal of GameDebug.gd
Add game project description
> Add ArgumentParser

- game/localisation/en_GB/menus.csv
- game/project.godot
- game/src/Autoload/SaveManager.gd
- game/src/GameMenu.tscn
- game/src/GameSession/GameSession.tscn
- game/src/GameSession/GameSessionMenu.gd
- game/src/GameSession/GameSessionMenu.tscn
- game/src/LobbyMenu/LobbyMenu.gd
- game/src/LobbyMenu/LobbyMenu.tscn
- game/src/LobbyMenu/LobbyPanelButton.gd
- game/src/LobbyMenu/LobbyPanelButton.tscn
- game/src/SaveLoadMenu/SaveLoadMenu.gd
- game/src/SaveLoadMenu/SaveLoadMenu.tscn
- game/src/SaveLoadMenu/SavePanelButton.gd
- game/src/SaveLoadMenu/SavePanelButton.tscn
- game/src/SaveLoadMenu/SaveResource.gd
- game/theme/default_theme.tres
- game/theme/game_session_menu.tres
Add SaveManager autoload singleton	
Add SaveLoadMenu to GameSession
Add Start Date Panel and Save Panel loading to LobbyMenu
Add LobbyPanelButton and SavePanelButton scene and scripts
Add SaveResource to handle saving and loading individual save files
Add localization for SaveLoadMenu
Expand localization for additions to LobbyMenu
Add ButtonContainer variation type to default theme
Fulfills: UI-82, UI-83, UI-84, UI-85, UI-87, UI-89, UI-90, UI-91, UI-92, UI-94, UIFUN-82, UIFUN-83, UIFUN-84, UIFUN-86, UIFUN-87, UIFUN-89, FS-28
> Add Save/Load Menu, save loading to LobbyMenu, and file saving

- game/src/LobbyMenu/LobbyMenu.gd
- game/src/LobbyMenu/LobbyMenu.tscn
- game/src/LobbyMenu/LobbyPanelButton.tscn
- game/src/SaveLoadMenu/SaveLoadMenu.gd
- game/src/SaveLoadMenu/SavePanelButton.tscn
Fix incorrect reference to UIFUN-83 as UIFUNC-83
See https://github.com/OpenVic2Project/OpenVic2/pull/110#pullrequestreview-1425218131 and https://github.com/OpenVic2Project/OpenVic2/pull/110#issuecomment-1546873933
Also fulfills: SS-18, UI-39, UI-40, UI-41, UI-86, UI-93, UIFUN-77, UIFUN-78, FS-8
> Fix incomplete #110 requirement documentation

- extension/src/Checksum.hpp
- game/art/economy/goods/README.md
- game/src/GameSession/MapControlPanel/MapControlPanel.tscn
- game/src/MusicConductor/MusicConductor.gd
- game/src/MusicConductor/MusicPlayer.gd
- game/src/OptionMenu/GeneralTab.tscn
- game/src/OptionMenu/VideoTab.tscn
Added comments for:
- UI-137, UI-141, UI-154, UI-155, UI-156, UI-160, UI-179, UI-548
- UIFUN-19, UIFUN-20, UIFUN-22, UIFUN-45, UIFUN-91
- DAT-8
- SND-2
- FS-39, FS-40, FS-41, FS-42, FS-43, FS-44, FS-45, FS-46, FS-47, FS-48, FS-49, FS-50,
- FS-51, FS-52, FS-53, FS-54, FS-55, FS-56, FS-57, FS-58, FS-59, FS-60, FS-61, FS-62,
- FS-63, FS-64, FS-65, FS-66, FS-67, FS-68, FS-69, FS-70, FS-71, FS-72, FS-73, FS-74,
- FS-75, FS-76, FS-77, FS-78, FS-79, FS-80, FS-81, FS-82, FS-83, FS-84, FS-85, FS-86
> Added requirement comments

- .github/workflows/builds.yml
Set build permissions to `write-all`
Fix missing archive_directory variable
Fix excessive archive path for zip release
> Fix Github Actions for release

- .github/workflows/builds.yml
- README.md
- extension/src/register_types.cpp
- game/bin/openvic.gdextension
- game/project.godot
- game/src/Game/LoadingScreen.gd
- game/src/Game/Menu/OptionMenu/SettingNodes/SettingCheckBox.gd
Fix deferred error in LoadingScreen.update_loading_screen
Fix pressed shadow variable warning in SettingCheckBox.gd
> Update to Godot 4.1

- SConstruct
Enables scons to generate `compile_commands.json` via `scons compiledb=yes compiledb` or `scons compiledb=yes compile_commands.json`
> Add compilation database support

- extension/src/GameSingleton.cpp
- extension/src/GameSingleton.hpp
- game/localisation/en_GB/mapmodes.csv
- game/localisation/en_GB/menus.csv
- game/src/Game/GameSession/MapControlPanel/MapControlPanel.gd
- game/src/Game/GameSession/ProvinceOverviewPanel/ProvinceOverviewPanel.gd
- game/src/Game/GameSession/ProvinceOverviewPanel/ProvinceOverviewPanel.tscn
- Update sim submodule to bring in Pop/Culture/Religion data structures (currently populated with hardcoded test instances)
- Added population density mapmode
Requirements implemented:
- MAP-33, UI-121, UI-562, UIFUN-141
> First pass at pops (test pops and density mapmode)

- game/src/Game/GameStart.gd
- game/src/Game/MusicConductor/MusicConductor.gd
- game/src/Game/MusicConductor/MusicPlayer.gd
Enable music on startup
Add sound option loading on startup
Fix MusicPlayer play button starting with incorrect text
> Add signals to MusicConductor

- README.md
Instructions are made to be easy to follow so that one can install and set up OpenVic, for Arch based distribution.
> Update README.md for Archlinux users

- game/src/Game/GameSession/MapView.gd
- I modified zoom to be centered on the mouse position, rather than the center of the viewport.
- Fixed bug with edge scrolling (scrolling now works when the mouse is outside the viewport.)
This is my first PR so please let me know if I overlooked any contributor rules.
> Implemented zoom-to-cursor functionality

- .vscode/launch.json
- README.md
- docs/contribution/cloning.md
- docs/contribution/debugging.md
- docs/contribution/rebasing.md
- docs/contribution/run-build-and-export.md
- docs/contribution/system-requirements.md
- docs/contribution/using-git-bisect.md
Simplify README.md
Add system-requirements.md
Add using-git-bisect.md
Add run-build-export.md
Add cloning.md
Add debugging.md
Add rebasing.md
Simplify .vscode/launch.json
> Fixup Documentation

- .astylesrc
- .clang-format
- astyle.sh
- clang-format.sh
- extension/src/openvic-extension/Checksum.hpp
- extension/src/openvic-extension/GameSingleton.cpp
- extension/src/openvic-extension/GameSingleton.hpp
- extension/src/openvic-extension/LoadLocalisation.cpp
- extension/src/openvic-extension/LoadLocalisation.hpp
- extension/src/openvic-extension/MapMesh.cpp
- extension/src/openvic-extension/Utilities.cpp
- extension/src/openvic-extension/Utilities.hpp
- extension/src/openvic-extension/register_types.cpp
- game/src/Game/Autoload/Argument/ArgumentParser.tscn
- game/src/Game/GameStart.gd
- game/src/Game/Menu/OptionMenu/ScreenModeSelector.gd
- Update SIM submodule to bring in a lot of changes
- Format standardisation
- Improved Godot executable CLI for setting base defines path + mod paths
> Lots of Changes

- extension/src/openvic-extension/Checksum.cpp
- extension/src/openvic-extension/Checksum.hpp
- extension/src/openvic-extension/GameSingleton.cpp
- extension/src/openvic-extension/GameSingleton.hpp
- extension/src/openvic-extension/MapMesh.cpp
- extension/src/openvic-extension/utility/ClassBindings.hpp
- extension/src/openvic-extension/utility/StringLiteral.hpp
depends on OpenVicProject/scripts#5
Adds OV_BIND_METHOD
Adds OV_BIND_SMETHOD
Adds OV_BIND_SMETHOD_L
Change _bind_methods to use ClassBinding helpers
Add utility/StringLiteral
Make `GameSingleton::singleton` inline
Move `OpenVic::Checksum` implementation to source file
Update scripts to [ce1aef8d7d9d5ba9851a1abdd981d3b796024079](https://github.com/OpenVicProject/scripts/commit/ce1aef8d7d9d5ba9851a1abdd981d3b796024079)
> Add ClassBinding helpers

- docs/simulation/calculations.yaml
Moved calculations from google sheets to yaml in repo as discussed on discord.
> Document calculations in YAML

- docs/simulation/calculations.yaml
I added Politics.Westernisation which describes the reform cost modifiers.
Also I moved the top level catagories in alphabetical order.
> Westernisation cost calculation

- docs/simulation/calculations.yaml
`<strata>_<need>_needs` scale the quantity a pop needs.
It does not affect social benefits.
> Document <strata>_<need>_needs modifier effect

- game/assets/localisation/locales/en_GB/menus.csv
- game/src/Game/Autoload/Argument/ArgumentParser.gd
- game/src/Game/GameStart.gd
- game/src/Game/GameStart.tscn
- game/src/Game/Menu/OptionMenu/ControlsTab.tscn
Move Localization.initialize to beginning of GameStart._ready
Move compatibility mode paths search to separate _setup_compatibility_mode_paths
Move _setup_compatibility_mode_paths call to GameStart._ready
Fix `Non-argument '%s' found, skipping.` warning for Godot command line arguments
> Add Victoria 2 Folder Picker dialog

- .github/workflows/builds.yml
Add max compression to exported artifacts
Make commit action merge libopenvic extension artifact files
Make release action merge libopenvic extension files into zip
> Update build workflow actions

- .github/workflows/builds.yml
Excludes:
- `.github` directory
- `.vscode` directory
- `LICENSE-EXCEPTIONS.md`
- `LICENSE.md`
- `README.md`
> Add workflow run limitations

- docs/simulation/calculations.yaml
Document factory hiring logic & EMPLOYMENT_HIRE_LOWEST
> Document HR

- README.md
See https://gitlab.archlinux.org/archlinux/packaging/packages/godot/-/issues/2
> Add warning for Arch users to avoid the Arch package

- game/project.godot
- game/src/Game/GameSession/MapView.gd
- game/src/Game/GameSession/TerrainMap.gdshader
Also disabled blender import project setting to stop warning every time the editor is opened.
> Smooth province edges and zoom tweaks

- game/src/Game/GameSession/NationManagementScreen/BudgetMenu.gd
I've declared the UI variables, linked them and used arbitrary values so that something can be seen. The labels increase in value over time and the sliders modify the value of the related label by being dragged.
I could add more logic to the buttons and tabs of the debt part but right now I wouldn't know how to proceed in that direction. Also, maybe I should leave public functions to modify the minimum and maximum values of the sliders.
> Preparation of the Budget Menu for the simulation data

- .github/workflows/builds.yml
- README.md
- extension/src/openvic-extension/utility/UITools.cpp
- extension/src/openvic-extension/utility/Utilities.hpp
Fix UITools.cpp float conversion warning
Add `OpenVic::Utilities::to_real_t(std::floating_point)`
Add _real user defined literal for real_t
> Update to Godot 4.2.2 Stable Release

- extension/src/openvic-extension/singletons/GameSingleton.cpp
- extension/src/openvic-extension/singletons/MenuSingleton.cpp
- extension/src/openvic-extension/singletons/MenuSingleton.hpp
- extension/src/openvic-extension/singletons/PopulationMenu.cpp
- game/src/Game/GameSession/NationManagementScreen/PopulationMenu.gd
Cache sort order for population menu columns sorted by localised string (pop type, culture, religion, location, and rebel faction).
> Cache sort order of localised population menu columns

- docs/simulation/calculations.yaml
For discussion and data see: https://discord.com/channels/1062018115275325480/1062021872545447936/1278648602020806707
> Document regiment xp gain

- docs/simulation/calculations.yaml
- Rewrite reinforcements to focus on regiment reinforcements instead of army reinforcements.
- Explain xp loss from reinforcements.
- Explain rounding
Try reading the reinforcement calculations and decide if they are explained well enough to implement.
> Document regiment reinforcements

- extension/src/openvic-extension/singletons/MenuSingleton.cpp
Check out the colonial power tooltip to see the overall modifiers affecting the current country (and right click on the map to select other countries).
> Update SIM repo to include resulant modifier calculation

- extension/src/openvic-extension/classes/GFXPieChartTexture.hpp
- extension/src/openvic-extension/singletons/MenuSingleton.cpp
- extension/src/openvic-extension/singletons/PopulationMenu.cpp
The [RGO PR](https://github.com/OpenVicProject/OpenVic-Simulation/pull/206) broke several bindings.
This PR fixes them so the UI can be compiled again.
> Fix UI bindings after RGO PR

- extension/src/openvic-extension/singletons/MenuSingleton.cpp
- game/src/Game/GameSession/ProvinceOverviewPanel.gd
Modifiers are out of scope of this PR.
> Use real RGO data

- .gitignore
- SConstruct
- extension/doc_classes/AssetManager.xml
- extension/doc_classes/Checksum.xml
- extension/doc_classes/GFXButtonStateHavingTexture.xml
- extension/doc_classes/GFXButtonStateTexture.xml
- extension/doc_classes/GFXCorneredTileSupportingTexture.xml
- extension/doc_classes/GFXMaskedFlagTexture.xml
- extension/doc_classes/GFXPieChartTexture.xml
- extension/doc_classes/GFXSpriteTexture.xml
- extension/doc_classes/GUIButton.xml
- extension/doc_classes/GUIIcon.xml
- extension/doc_classes/GUIIconButton.xml
- extension/doc_classes/GUILabel.xml
- extension/doc_classes/GUIListBox.xml
- extension/doc_classes/GUIMaskedFlag.xml
- extension/doc_classes/GUIMaskedFlagButton.xml
- extension/doc_classes/GUINode.xml
- extension/doc_classes/GUIOverlappingElementsBox.xml
- extension/doc_classes/GUIPieChart.xml
- extension/doc_classes/GUIProgressBar.xml
- extension/doc_classes/GUIScrollbar.xml
- extension/doc_classes/GUITextureRect.xml
- extension/doc_classes/GameSingleton.xml
- extension/doc_classes/LoadLocalisation.xml
- extension/doc_classes/MapMesh.xml
- extension/doc_classes/MenuSingleton.xml
- extension/doc_classes/ModelSingleton.xml
- extension/doc_classes/SoundSingleton.xml
Depends on #307
See godotengine/godot-cpp#1374 for use
> Add in-editor documentation support

- extension/src/openvic-extension/utility/UITools.cpp
- game/src/Game/GameSession/Ledger.gd
- game/src/Game/GameSession/Menubar.gd
- game/src/Game/GameSession/NationManagementScreen/BudgetMenu.gd
- game/src/Game/GameSession/NationManagementScreen/DiplomacyMenu.gd
- game/src/Game/GameSession/NationManagementScreen/MilitaryMenu.gd
- game/src/Game/GameSession/NationManagementScreen/PoliticsMenu.gd
- game/src/Game/GameSession/NationManagementScreen/PopulationMenu.gd
- game/src/Game/GameSession/NationManagementScreen/ProductionMenu.gd
- game/src/Game/GameSession/NationManagementScreen/TechnologyMenu.gd
- game/src/Game/GameSession/NationManagementScreen/TradeMenu.gd
- game/src/Game/GameSession/SearchPanel.gd
- game/src/Game/GameSession/Topbar.gd
Set `mouse_filter` in generate_window to `MOUSE_FILTER_IGNORE`
Click Masks added to:
* Ledger
* MenuBar
* BudgetMenu
* DiplomacyMeny
* MilitaryMenu
* PoliticsMenu
* PopulationMenu
* ProductionMenu
* TechnologyMenu
* TradeMenu
* SearchPanel
> Add click masks to GameSession UI

- extension/src/openvic-extension/utility/UITools.cpp
- game/project.godot
- game/src/Game/GameSession/Menubar.gd
- game/src/Game/GameSession/Topbar.gd
Depends on OpenVicProject/OpenVic-Simulation#244
Add pause menu shortcut
Add time speed up, time speed down, and time pause shortcuts
> Add shortcut GUI support

- extension/doc_classes/GameSingleton.xml
- extension/src/openvic-extension/classes/GUIListBox.cpp
- extension/src/openvic-extension/singletons/GameSingleton.cpp
- extension/src/openvic-extension/singletons/GameSingleton.hpp
- extension/src/openvic-extension/singletons/MapItemSingleton.cpp
- extension/src/openvic-extension/singletons/MenuSingleton.cpp
- extension/src/openvic-extension/singletons/MenuSingleton.hpp
- extension/src/openvic-extension/utility/Utilities.cpp
- extension/src/openvic-extension/utility/Utilities.hpp
- game/src/Game/GameSession/MapView.gd
- game/src/Game/GameSession/ModelManager.gd
- game/src/Game/GameSession/NationManagementScreen/BudgetMenu.gd
- game/src/Game/GameSession/NationManagementScreen/PopulationMenu.gd
- game/src/Game/GameSession/SearchPanel.gd
- game/src/Game/GameSession/Topbar.gd
- game/src/Game/Menu/LobbyMenu/LobbyMenu.gd
- game/src/Game/Menu/LobbyMenu/LobbyPanelButton.gd
- game/src/Game/Menu/LobbyMenu/LobbyPanelButton.tscn
- game/src/Game/Menu/SaveLoadMenu/SavePanelButton.gd
- game/src/Game/Menu/SaveLoadMenu/SavePanelButton.tscn
- game/src/Game/Model/UnitModel.gd
Also fixes some model attachment errors and brings in SIM changes that fix duplicate core errors
> Starting bookmark position, search panel enter, cleanup

- .github/workflows/builds.yml
Implements workaround for awalsh128/cache-apt-pkgs-action#145
> Fix deprecated upload artifact CI error

- pyproject.toml
Fixes typos pre-commit errors for #363
> Fix typos xml ignore regex

- game/src/Game/Menu/LobbyMenu/LobbyMenu.gd
- game/src/Game/Menu/LobbyMenu/LobbyMenu.tscn
> Add escape back shortcut to LobbyMenu

- extension/doc_classes/GameSingleton.xml
- extension/doc_classes/PlayerSingleton.xml
- extension/src/openvic-extension/register_types.cpp
- extension/src/openvic-extension/singletons/GameSingleton.cpp
- extension/src/openvic-extension/singletons/GameSingleton.hpp
- extension/src/openvic-extension/singletons/MenuSingleton.cpp
- extension/src/openvic-extension/singletons/MilitaryMenu.cpp
- extension/src/openvic-extension/singletons/PlayerSingleton.cpp
- extension/src/openvic-extension/singletons/PlayerSingleton.hpp
- extension/src/openvic-extension/singletons/TradeMenu.cpp
- game/src/Game/GameSession/GameSession.gd
- game/src/Game/GameSession/MapView.gd
- game/src/Game/GameSession/ProvinceOverviewPanel.gd
- game/src/Game/Menu/LobbyMenu/LobbyMenu.gd
Waiting on [OpenVic-Simulation#319](https://github.com/OpenVicProject/OpenVic-Simulation/pull/319) to be merged
> Add PlayerSingleton managing player country and selected province

- extension/src/openvic-extension/singletons/PopulationMenu.cpp
Depends on https://github.com/OpenVicProject/OpenVic-Simulation/pull/354
> Name change to get_unemployment_fraction

- extension/src/openvic-extension/singletons/SoundSingleton.cpp
- extension/src/openvic-extension/singletons/SoundSingleton.hpp
> Replace load_godot_wav with `AudioStreamWAV::load_from_file`

- extension/src/openvic-extension/singletons/SoundSingleton.cpp
- extension/src/openvic-extension/singletons/SoundSingleton.hpp
- Relies on #417
Remove load_godot_mp3
> Replace load_godot_mp3 with `AudioStreamMP3::load_from_file`

- .github/workflows/builds.yml
- .github/workflows/cache_cleanup.yml
Fix CHANGED_FILES in CI
Simplify concurrency group in builds workflow
Remove forced check in builds workflow
Add emoji to builds workflow name
Add cache_cleanup on PR close
> Add merge_group support to builds workflow

- docs/simulation/calculations.yaml
Modifiers from technology are taken into account when determining province size.
> Document rgo size modifiers

- extension/src/openvic-extension/singletons/AssetManager.cpp
- extension/src/openvic-extension/singletons/AssetManager.hpp
- extension/src/openvic-extension/singletons/CursorSingleton.cpp
- extension/src/openvic-extension/singletons/CursorSingleton.hpp
- extension/src/openvic-extension/singletons/SoundSingleton.cpp
- extension/src/openvic-extension/singletons/SoundSingleton.hpp
Remove optional storage of godot packed arrays
> Remove optional storage of godot::Ref values

- .gitignore
The launch.json is a local config file which you need to modify to debug locally. It is not part of the source code.
> Add vscode launch.json to gitignore

- extension/doc_tools/make_rst.py
- extension/doc_tools/patches/make_rst.patch
> Update make_rst.py's Godot version to 4.4.1

- game/src/Autoload/Resolution.gd
- game/src/Autoload/WindowOverride.gd
> Add editor embedded game window support

- game/src/Systems/Startup/GameStart.gd
- game/src/UI/GameMenu/MainMenu/MainMenu.gd
- game/src/UI/GameMenu/OptionMenu/OptionsMenu.gd
- game/src/UI/GameMenu/OptionMenu/SettingNodes/SettingOptionButton.gd
- game/src/UI/Session/PauseMenu/PauseMenu.gd
See [Handling quit requests](https://docs.godotengine.org/en/stable/tutorials/inputs/handling_quit_requests.html) for the recommended way to handle quitting.
> Add `NOTIFICATION_WM_CLOSE_REQUEST` quit propagation
