game/src/GameMenu.gd, game/src/GameMenu.tscn, game/src/LobbyMenu/LobbyMenu.gd, game/src/LobbyMenu/LobbyMenu.tscn, game/src/MainMenu/MainMenu.gd
The lobby is opened by clicking "new game" in the main menu. Currently only two start dates are in the listbox, but the intention is for saved games to be present as well. Most of the space on the right-hand panel is reserved for information about the selected country and other players. The purpose of the separation is to allow a map to be rendered behind the menu.
The start button can be pressed only after a save has been selected.
Save games/start dates don't actually get loaded yet, since obviously the actual underlying game data doesn't exist yet.
=> Add skeleton for Game Lobby Menu

game/addons/keychain/assets/add.svg.import, game/addons/keychain/assets/close.svg.import, game/addons/keychain/assets/edit.svg.import, game/addons/keychain/assets/folder.svg.import, game/addons/keychain/assets/joy_axis.svg.import, game/addons/keychain/assets/joy_button.svg.import, game/addons/keychain/assets/keyboard.svg.import, game/addons/keychain/assets/keyboard_physical.svg.import, game/addons/keychain/assets/mouse.svg.import, game/addons/keychain/assets/shortcut.svg.import
A change happened in the release candidates for Godot that changed the compression settings for texture imports
=> Update Keychain SVG imports to Godot 4 RC 5

docs/project-file-structure.md
Added to the Project Structure Documentation from suggestions.
* Asset File Organization
* Data File Organization
* File & Directory naming conventions
* Definitions
* Linux user/ directory location - update in reqs if not done yet
The asset file organization should really be looked at by someone in the art team to make sure there is nothing ridiculous in there. However for the initial stages of the project, it should be sufficient
I've also added the use of a custom file extension for data files, because it is neater than having .txt files littered around the project. This will hopefully make it easier to understand what is actually used by the engine and not just random files in the directory
=> Modify Project Structure Documentation

game/project.godot, game/src/Autoload/GameDebug.gd
Fulfills requirement SS-56
Debug mode may be activated by calling the application (`<app>`) like so:
```
<app> --game-debug
<app> -- --game-debug
<app> -- -d
<app> -- --debug
<app> -- --debug-mode
<app> ++ --game-debug
<app> ++ -d
<app> ++ --debug
<app> ++ --debug-mode
```
Godot supports [reading command line arguments](https://docs.godotengine.org/en/stable/classes/class_os.html#class-os-method-get-cmdline-args), but it also interprets [command line arguments for the engine](https://docs.godotengine.org/en/stable/tutorials/editor/command_line_tutorial.html) before the game, (for example `--debug` is an engine interpreted command line argument) in order to guarantee no overlap in engine command line arguments and game command line arguments, `--` or `++` may be used, I left `--game-debug` …
=> Add Debug Mode

game/src/GameMenu.gd, game/src/GameMenu.tscn, game/src/LocaleButton.gd, game/src/MainMenu/MainMenu.gd, game/src/MainMenu/MainMenu.tscn, game/src/OptionMenu/AutosaveIntervalSelector.gd, game/src/OptionMenu/GeneralTab.gd, game/src/OptionMenu/GeneralTab.tscn, game/src/OptionMenu/OptionsMenu.gd, game/src/OptionMenu/OptionsMenu.tscn, game/src/OptionMenu/QualityPresetSelector.gd, game/src/OptionMenu/RefreshRateSelector.gd, game/src/OptionMenu/VideoTab.gd, game/src/OptionMenu/VideoTab.tscn
Fixed up a lot of the UI for the options menu, added some missing reqs. This is only a beginning, once we have actual UI elements for the options menu it needs to be added in, and the settings are currently visual-only, we need to look at designing a singleton settings state object from which to pull the users preferences in both gdscript and C++.
This PR covers UI-48, UI-50, UI-15, UI-18, UI-21, UIFUN-19, UIFUN-20, UIFUN-22, & UIFUN-45
=> Polishing and Adding to Options Menu

game/src/GameMenu.gd, game/src/GameMenu.tscn
Export variables are less capable to break and can be fixed from the Godot inspector without opening up the scripts.
=> Refactor GameMenu to rely on export variables

.github/workflows/builds.yml, README.md
Remove specific Godot version references for non-links in README.md
Might need to delete your `.godot` directory, compile scons, and then reimport the project again.
=> Update to Godot 4.0.2 Stable Release

.clang-format
This `.clang-format` will be used in the future for automatic formatting.
The auto-formatting will be addressed between dev cycle 2 and 3.
=> Added a .clang-format for formatting use

.clang-format
Altering .clang-format to make compliant with clang-format v10.0.0; formerly v16.0.1 compliant
=> Altering .clang-format to make compliant with clang-format 10.0.0

game/src/GameSession/GameSession.tscn, game/src/GameSession/MapView.gd, game/src/GameSession/ProvinceOverviewPanel.gd, game/src/GameSession/ProvinceOverviewPanel.tscn, game/src/GameSession/TerrainMap.gdshader
- Province highlight on selection/hover is now a 10% shift to white for each, rather than an increase in the proportion of the province colour used vs the terrain colour.
- Province Overview Panel now blocks mouse hover over provinces, just like Map Control Panel
- Made `pixels_per_terrain_tile` a constant, eventually this should take both the map dims and the terrain texture dims into account.
=> Better province highlight on selection/hover.

game/localisation/en_GB/provinces.csv
Tweak localization keys so that names will show up properly on the province overview panel
=> Fix display names for North American provinces

docs/general-program-architecture.md
An issue was present in the [general-program-architecture mermaid diagram](https://github.com/OpenVic2Project/OpenVic2/blob/main/docs/general-program-architecture.md) causing an issue when rendering the doc.
Empty `Message text` caused an error in mermaid (after the  "load previous save game" step). Putting a space fixes this issue too, but that looks a little ugly:
=> [Bug] [Documentation] Mermaid render error

game/localisation/en_GB/menus.csv, game/localisation/en_US/menus.csv, game/localisation/fr_FR/menus.csv, game/project.godot, game/src/Autoload/GuiScale.gd, game/src/Autoload/Resolution.gd, game/src/GameSession/MapView.gd, game/src/OptionMenu/GuiScaleSelector.gd, game/src/OptionMenu/VideoTab.tscn
Adds a Video Settings menu option to change the GUI scale.
Example use: With Windows 1080p, select 1.5x UI scaling. This setting persists between the game and the main menu.
- Adds Localization to the three current files
- Adds the GUI scale selection button to the video settings menu
- Changes godot's get_tree().root.content_scale_factor to set the GUI scale
TODO:
- French and en_gb localizations need to be verified
- Line 37 of GuiScaleSelector.gd `default_value = ProjectSettings.get_setting("display/window/stretch/scale")` needs to be verified for correct functionality
- This commit generally needs QA/feedback
=> Add UI scaling through menu option

LICENSE-EXCEPTIONS.md
Clarifying that artistic works are licensed under [Attribution-ShareAlike 4.0 International](https://creativecommons.org/licenses/by-sa/4.0/legalcode) license
=> Add clarification on licensing of artistic works

game/src/MusicConductor/MusicConductor.tscn, game/src/OptionMenu/SettingNodes/SettingHSlider.gd
Fix MusicConductor ignoring MUSIC_BUS
This fixes volume sliders being ignored when loaded at zero, which means if you set the slider to zero and reloaded the game, it would act as if the volume was at 100.
=> Fix SettingHSlider not loading properly on default values

docs/contribution-quickstart-guide.md, docs/project-file-structure.md, docs/styleguide-cpp.md
Changing instances of the term "OpenVic2" to just "OpenVic" within the documentation.
=> Changing "OpenVic2" to "OpenVic" in documentation

game/localisation/en_GB/menus.csv, game/localisation/en_US/menus.csv, game/localisation/fr_FR/menus.csv, game/src/GameSession/GameSession.tscn, game/src/OptionMenu/ResolutionSelector.gd, game/src/OptionMenu/VideoTab.tscn
Fix GameSession UI node order
- Fulfills requirements UI-873, UIFUN-301, UIFUN-302
- Adds a dialog popup to the videotab under the options menu. This dialog appears when the user selects a new resolution, asking them if they want to keep the resolution. Selecting 'No' or letting the dialog's timer expire will revert the resolution, while selecting 'yes' will keep the newly selecting resolution.
- Localized, but french isn't my native language so it needs to be double checked.
- Motivation: if the user messes up their resolution, they can now recover gracefully.
- Also: Changed GameSessionMenu to be lower in GameSession's hierarchy so that it appears on-top of any overlapping UI elements (achievable with a bad UI-scaling setting).
- The KeepChangesDialog.tscn is designed to be somewhat …
=> Add Keep Resolution Dialog

game/src/Autoload/Resolution.gd, game/src/OptionMenu/GeneralTab.tscn, game/src/OptionMenu/GuiScaleSelector.gd, game/src/OptionMenu/MonitorDisplaySelector.gd, game/src/OptionMenu/ResolutionRevertDialog.gd, game/src/OptionMenu/ResolutionSelector.gd, game/src/OptionMenu/ScreenModeSelector.gd, game/src/OptionMenu/SettingNodes/SettingOptionButton.gd, game/src/OptionMenu/SettingNodes/SettingRevertButton.gd, game/src/OptionMenu/VideoTab.tscn
Fix recursion bug caused by invalid default value in `reset_setting` Add `option_selected` signal to SettingOptionButton
Add `no_emit` bool defaulted to false for `SettingOptionButton.reset_setting`
Add push_error for failing to generate option as well Generalize ResolutionRevertDialog functionality
Add Resolution `resolution_added`, `resolution_changed`, and `window_mode_changed` signals
Add `get_resolution_name` to Resolution
Change ResolutionSelector `_sync_resolutions` to use `Resolution.resolution_added` signal
Move Resolution display_name functionality to ResolutionSelector
Add SettingRevertButton to automatically handle revert setting behavior
Rename VideoTab VBoxContainer/GridContainer to VideoSettingGrid
Rename VideoTab VBoxContainer to VideoSettingList
Remove …
=> Add revert dialog functionality to ScreenModeSelector

.github/workflows/builds.yml
Should make changing the Godot version, even for dev, alpha, beta, and release candidates trivial.
As an example to support the current 4.1 dev version all we need to do is:
```
GODOT_VERSION_PREFIX: dev4/Godot_v
GODOT_VERSION_SUFFIX: dev4
GODOT_VERSION: 4.1
```
When 4.1 comes out would only need to make it:
```
GODOT_VERSION: 4.1
```
=> Add environment variables for trivial Godot updates

game/src/Game/Autoload/Argument/ArgumentParser.gd, game/src/Game/Autoload/Argument/ArgumentParser.tscn, game/src/Game/Autoload/Events.gd, game/src/Game/Autoload/Events/GameDebug.gd
Fix ArgumentParser ignoring full name boolean arguments
Add warning for ArgumentParser parsing a non-boolean standalone argument
Move SS-56 requirement to ArgumentParser scene
Add has_argument_support, get_argument, and set_argument to ArgumentParser
Update `GameDebug.gd` to rely on `ArgumentParser.get_argument`
Update `Events.gd` to rely on `ArgumentParser.get_argument`
=> Fix ArgumentParser excluding last character for arg key

.github/actions/mingw-cache/action.yml, .github/actions/openvic-build/action.yml, .github/actions/openvic-cache/action.yml, .github/workflows/builds.yml, SConstruct
Add openvic-build action
Add openvic-cache action
Add mingw-cache action
Add verbose and progress Scons options to SConstruct
This is completely based on how Godot implemented caching with Scons
This should radically speed up extension compilation times in most cases
With this and #136 Github checks shrink down to 8 minutes in total from 27 minutes.
=> Add Scons cache support

.github/workflows/builds.yml
The first run will not change anything, but subsequent runs will be speed up on export and on debug pck export.
With this and #137 Github checks shrink down to 8 minutes in total from 27 minutes.
=> Add Godot binary/template cache support

game/project.godot, game/src/Game/Autoload/Argument/ArgumentParser.gd, game/src/Game/Autoload/Events.gd, game/src/Game/Autoload/Events/GameDebug.gd, game/src/Game/Autoload/Events/Loader.gd, game/src/Game/Autoload/Events/Options.gd, game/src/Game/Autoload/GameLoader.gd, game/src/Game/GameSession/MapControlPanel/Minimap.gd, game/src/Game/GameSession/MapView.gd, game/src/Game/GameSession/ProvinceOverviewPanel/ProvinceOverviewPanel.gd, game/src/Game/GameStart.gd, game/src/Game/GameStart.tscn, game/src/Game/GlobalClass/GameDebug.gd, game/src/Game/GlobalClass/Localisation.gd, game/src/Game/GlobalClass/ShaderManager.gd, game/src/Game/LoadingScreen.gd, game/src/Game/LocaleButton.gd, game/src/Game/Menu/OptionMenu/MonitorDisplaySelector.gd, game/src/Game/Menu/OptionMenu/ResolutionSelector.gd, game/src/Game/Menu/OptionMenu/SettingRevertDialog.gd
Remove GameDebug, Localization, and ShaderManager from Events.gd
Renamed OptionsSingleton class_name to OptionsEventsObject
Add Events.Loader to handle Loader events (which are global signals)
Make GameDebug singleton with static functions and property
Make Localization functions static
Move ShaderManager variable to GameLoader
Move Events._define_filepaths_dict to GameLoader.define_filepaths_dict
Move game initialization from LoadingScreen.gd and Events.gd to GameStart.gd
Attach GameStart.gd to GameStart.tscn root
Make LoadingScreen generalized and so it is reusable
Remove class_name from LoaderingScreen.gd
=> Add GameLoader Autoload to handle global loading data

.github/actions/openvic-env/action.yml, .github/actions/openvic-env/commit-environment.js, .github/actions/openvic-env/url-environment.sh, .github/workflows/builds.yml, README.md
Add bash-based Godot URL environment variable handling to openvic-env action
Separate Commit environment variable handling in openvic-env to self-contained js file.
If `GODOT_BASE_DOWNLOAD_URL`, `GODOT_VERSION`, and `GODOT_VERSION_TYPE` are all set, this will then set a `GODOT_LINUX_URL` and `GODOT_TEMPLATE_URL` environment variable that points to the proper download path for the template and x86_64 linux version of the respective binaries.
`GODOT_BASE_DOWNLOAD_URL` must be either `downloads.tuxfamily.org/godotengine` or `github.com/godotengine` (must point to a repo, accounts for also pointing to releases or releases/download) for now.
Errors if either `GODOT_LINUX_URL` or `GODOT_TEMPLATE_URL` is not set.
If `GODOT_LINUX_URL` environment variable is already set to a non-empty value, it …
=> Update to Godot 4.1.1 Stable Release

.gitmodules, extension/src/GameSingleton.cpp, game/addons/openvic-plugin/ReleaseExportEditorPlugin.gd, game/project.godot, game/src/Game/Autoload/Events/Options.gd, game/src/Game/Autoload/Resolution.gd, game/src/Game/GameSession/GameSession.gd, game/src/Game/GameSession/GameSpeedPanel.gd, game/src/Game/GameSession/GameSpeedPanel.tscn, game/src/Game/GameSession/MapControlPanel/MapControlPanel.gd, game/src/Game/GameSession/ProvinceOverviewPanel/ProvinceOverviewPanel.gd, game/src/Game/LocaleButton.gd, game/src/Game/LocaleButton.tscn, game/src/Game/Menu/MainMenu/MainMenu.tscn, game/src/Game/Menu/MainMenu/ReleaseInfoBox.gd, game/src/Game/Menu/MainMenu/ReleaseInfoBox.tscn, game/src/Game/Menu/OptionMenu/OptionsMenu.gd, game/src/Game/Menu/OptionMenu/ResolutionSelector.gd, game/src/Game/Menu/OptionMenu/ScreenModeSelector.gd, game/src/Game/Menu/OptionMenu/SettingNodes/SettingOptionButton.gd, game/src/Game/Menu/OptionMenu/SoundTab.gd, game/src/Game/MusicConductor/MusicConductor.gd, game/src/Game/MusicConductor/MusicPlayer.gd, game/src/Game/MusicConductor/MusicPlayer.tscn
- Fixed some unused arg warnings
- Added key shortcuts for pausing (UIFUN-90) and changing speed
- Fixed error on missing `settings.cfg`, e.g. when starting the game for the first time/with no OpenVic `app_data` folder
- Moved `user://` from `Godot/app_userdata/OpenVic` into a custom folder `OpenVic` folder (FS-2, FS-20, FS-21, FS-22)
- Updated `openvic-dataloader` submodule folder
Added comments for already implemented requirements:
- SS-25, SS-26, SS-37, SS-38, SS-39, SS-87, SS-104, SS-105, SS-106, SS-107, SS-127, SS-128, SS-130, SS-131, SS-132, SS-133
- UI-105, UI-108, UI-109, UI-110, UI-600, UI-869, UI-870, UI-871, UI-872, UI-895, UI-896, UI-898, UI-899
- UIFUN-13, UIFUN-71, UIFUN-72, UIFUN-73, UIFUN-93, UIFUN-94, UIFUN-95, UIFUN-140, UIFUN-295, UIFUN-296, UIFUN-297, UIFUN-298, …
=> Tidying: missing req comments, submodules, hotkeys, user data folder

SConstruct, scripts/build/cache.py, scripts/build/glob_recursive.py, scripts/build/option_handler.py
Placed in scripts/build
Streamline scons options with OptionsClass in scripts/build/option_handler.py
Move `show_progress` cache function to scripts/build/cache.py
Move `GlobRecursive` function to scripts/build/glob_recursive.py
Make environment clone of godot-cpp's build - Prevents environment leakage into godot-cpp
=> Separate build functions from SConstruct

game/project.godot, game/src/Game/Autoload/Argument/ArgumentParser.gd, game/src/Game/Autoload/WindowOverride.gd, game/src/Game/GameStart.gd
Hides window for help argument (`./Openvic -- --help`)
Hides window until video options loading is complete
Makes Window handling way more convenient, can delay a visible window until after everything has been processed and prepared to display it.
Needs Windows and Mac testing.
=> Add Window Override

.github/workflows/builds.yml, README.md, SConstruct
depends on OpenVicProject/scripts#6
depends on godotengine/godot-cpp#1306
Requires later fix for dependencies to update scripts submodule to OpenVicProject/scripts#6.
=> Update to Godot 4.1.3 Stable Release

game/src/Game/GameStart.gd
Add type hints to GameStart.gd constants
Seperate section_name and setting_name from Nodes group in inspector
Prefer callable's called_deferred to string caller in GameStart.gd
Change `GameStart._initialize_game` to use change_scene_to_packed and GameMenuScene constant to change scene instead
This seems to result in a quicker transition from loading screen to main menu.
=> Add constant GameMenuScene preload to GameStart.gd

extension/src/openvic-extension/classes/GFXMaskedFlagTexture.cpp, extension/src/openvic-extension/classes/GFXPieChartTexture.cpp, extension/src/openvic-extension/singletons/AssetManager.cpp, extension/src/openvic-extension/singletons/AssetManager.hpp, extension/src/openvic-extension/singletons/GameSingleton.cpp, extension/src/openvic-extension/singletons/GameSingleton.hpp, extension/src/openvic-extension/singletons/LoadLocalisation.cpp, extension/src/openvic-extension/utility/UITools.cpp, extension/src/openvic-extension/utility/Utilities.cpp
- Replace most instances of `return nullptr;` or `return FAILED;`, and accompanying `UtilityFunctions::push_error` messages, with `ERR_FAIL_*` macros. Most remaining uses of `FAILED` and `UtilityFunctions::push_error` are in contents where a local error variable is set to `FAILED`, rather than returning immediately, for example:
```c+++
if (!dataloader.set_roots(roots)) {
Logger::error("Failed to set dataloader roots!");
err = FAILED;
}
```
- Changed some `String` and `StringName` arguments to use const references, and changed `String` variables to `StringName`s when they will be used to fill a `StringName` function argument.
=> Use `ERR_FAIL_*` macros where possible

.gitignore, game/src/Game/Autoload/Argument/ArgumentOption.gd, game/src/Game/Autoload/Argument/ArgumentParser.gd, game/src/Game/Autoload/Argument/ArgumentParser.tscn, game/src/Game/GameStart.gd
- Added `TYPE_PACKED_STRING_ARRAY` command line option type, which is basically just a string option that can be used multiple times without overwriting.
- Added `--mod` or `-m` option, which can be used multiple times, each time adding a mod's name (not including the `/mod/` part of its path). Mods are loaded in reverse order, so the last mod added will have the highest priority when `Dataloader` looks up files.
- Updates the SIM submodule to the `registry-template-fun` branch because that removes a `"dataloader/NodeTools.hpp"` include which was breaking the Github Action builds.
=> Added mod command line option

extension/src/openvic-extension/singletons/GameSingleton.cpp, extension/src/openvic-extension/singletons/GameSingleton.hpp, game/src/Game/GameSession/MapView.gd, game/src/Game/GameSession/MapView.tscn, game/src/Game/GameSession/ProvinceOverviewPanel.gd, game/src/Game/GameSession/TerrainMap.gdshader, game/src/Game/GameSession/Topbar.gd, game/src/Game/GlobalClass/ShaderManager.gd
- Changed water to use the water colormap rather than a solid blue texture. That texture is now red as a warning if it's ever accidentally used, it still needs to exist so we don't have to branch to avoid reading a terrain tile array texture for water pixels.
- Added overlay parchment/far view to the map shader, including a `parchment_mix` uniform float which controls the blending of the near (0) and far (1) map types.
- Refactored map shader to only blend terrain from the four corners of the pixel, but to only calculate a single province colour value. This creates a pixelated look along boundaries between different province colours, but that will be hidden by province/state/country borders in a future PR.
- Added `_zoom_parchment_threshold` to determine at what point to switch from the …
=> Added overlay parchment map and refactored map shader

extension/src/openvic-extension/utility/Utilities.cpp
Also change `Utilities::date_to_formatted_string` to account for `Date::get_month_name` now returning a `std::string_view`
=> Update sim and script submodules

game/assets/graphics/theme/main_menu.tres, game/assets/localisation/locales/en_GB/menus.csv, game/assets/localisation/locales/en_US/menus.csv, game/src/Game/Menu/MainMenu/ReleaseInfoBox.gd, game/src/Game/Menu/MainMenu/ReleaseInfoBox.tscn
Add clarifications to ReleaseInfoBox buttons
Will be used to correct some of the TODOs in #203
Clicking game info for the PR action CI will result in:
```
OpenVic v0.02_Mappa_Mundi (14be1eb) [Godot 4.2.1-stable (official)] - Arch Linux 2024-02-05T19:09:33 - X11 - ...
```
for me
=> Add GameInfo button to MainMenu

extension/src/openvic-extension/classes/GFXIconTexture.cpp, extension/src/openvic-extension/classes/GFXPieChartTexture.cpp, extension/src/openvic-extension/classes/GUINode.cpp, extension/src/openvic-extension/classes/GUINode.hpp, extension/src/openvic-extension/utility/UITools.cpp, extension/src/openvic-extension/utility/UITools.hpp, extension/src/openvic-extension/utility/Utilities.cpp, extension/src/openvic-extension/utility/Utilities.hpp, game/src/Game/Autoload/Events.gd, game/src/Game/Autoload/Events/NationManagementScreens.gd, game/src/Game/GameSession/GameSession.tscn, game/src/Game/GameSession/NationManagementScreen/BudgetMenu.gd, game/src/Game/GameSession/NationManagementScreen/DiplomacyMenu.gd, game/src/Game/GameSession/NationManagementScreen/MilitaryMenu.gd, game/src/Game/GameSession/NationManagementScreen/PoliticsMenu.gd, game/src/Game/GameSession/NationManagementScreen/PopulationMenu.gd, game/src/Game/GameSession/NationManagementScreen/ProductionMenu.gd, game/src/Game/GameSession/NationManagementScreen/TechnologyMenu.gd, game/src/Game/GameSession/NationManagementScreen/TradeMenu.gd, game/src/Game/GameSession/ProvinceOverviewPanel.gd, game/src/Game/GameSession/Topbar.gd, game/src/Game/GameStart.gd, game/src/Game/GlobalClass/NationManagement.gd
- Added support for getting `GUI::Position`s from GDScript.
- Added placeholder UI elements (semi-transparent `godot::ColorRect`s) for:
- `GUI::ListBox` - blue
- `GUI::TextEditBox` - green
- `GUI::Scrollbar` - red
- Added `NationManagement` global class containing `Screen` enum, accessed as `NationManagement.Screen`.
- Added `NationManagementScreensEventsObject` for handling current active screen, update signal and open, close, toggle functions.
- Added nation mangement screen `GUINode`s as children of `Topbar` for easier organisation. Each currently generates its base scene and connects its close button. They have basic scripts (which would've used a shared base class, but Godot doesn't like double-extending GDExtension classes for some reason), each will need more work to be fully wired …
=> Basic Nation Management Screen framework

extension/src/openvic-extension/classes/GUIListBox.cpp, extension/src/openvic-extension/classes/GUIListBox.hpp, extension/src/openvic-extension/classes/GUINode.cpp, extension/src/openvic-extension/classes/GUINode.hpp, extension/src/openvic-extension/classes/GUIScrollbar.cpp, extension/src/openvic-extension/classes/GUIScrollbar.hpp, extension/src/openvic-extension/register_types.cpp, extension/src/openvic-extension/singletons/AssetManager.cpp, extension/src/openvic-extension/singletons/AssetManager.hpp, extension/src/openvic-extension/singletons/GameSingleton.cpp, extension/src/openvic-extension/singletons/GameSingleton.hpp, extension/src/openvic-extension/utility/UITools.cpp, game/assets/localisation/locales/en_GB/menus.csv, game/assets/localisation/locales/ru_RU/menus.csv, game/src/Game/GameSession/MapControlPanel/MapControlPanel.tscn, game/src/Game/GameSession/ProvinceOverviewPanel.gd, game/src/Game/GameSession/Topbar.gd, game/src/Game/GameStart.gd
- Add `GUIListBox`, with scrollbar/scrolling and automatic child arrangment (which takes child visibility into account).
- `GUIScrollbar` tweaks:
- length override, for `GUIListBox`'s scrollbars which need to have their lengths adjusted.
- default start at 0 so that scrollbars start at the top rather than middle.
- made range limits always min/max for non-range limited scrollbars.
- Connect textures' `changed` signal to `StyleBoxTexture`s' `emit_changed` function so that calling `set_icon_index` causes buttons to redraw.
- Flipped progress bar textures vertically to match Vic2, using a new `AssetManager` arg `bool flip_y`, and set their default max value to `1.0`.
- Made icons rotatable.
- Added `format_province_name` helper function.
- Fixed bug with default install directory search …
=> Add GUIListBox + UI improvements

extension/src/openvic-extension/classes/GFXButtonStateTexture.cpp, extension/src/openvic-extension/classes/GFXButtonStateTexture.hpp, extension/src/openvic-extension/classes/GFXPieChartTexture.cpp, extension/src/openvic-extension/classes/GFXPieChartTexture.hpp, extension/src/openvic-extension/classes/GUIListBox.cpp, extension/src/openvic-extension/classes/GUIListBox.hpp, extension/src/openvic-extension/classes/GUIScrollbar.cpp, extension/src/openvic-extension/classes/GUIScrollbar.hpp, extension/src/openvic-extension/utility/UITools.cpp
- UI work needed for Population Menu:
- Label padding (`border_size` + 1px of default horizontal padding)
- Progressbar min/max/steps standardised to `[0, 1]` with `0.01` steps.
- Piechart slices changed to key item definition order and their positioning changed to start on the positive x-axis (right) and continue around anti-clockwise.
- `SELECTED` button state texture added (all components reduced by `0.3`).
- `GUIListBox` reworked to use a calculated max scroll index (either from all current child elements or for a `fixed` item count and height), with a `scroll_index_changed` signal added and it's `GUIScrollbar` changed to an internal child (so by default it won't contribute to child count or lookup by index).
=> Assorted UI Changes (in preparation for Population Menu)

extension/src/openvic-extension/classes/GFXMaskedFlagTexture.hpp, extension/src/openvic-extension/classes/GFXPieChartTexture.hpp, extension/src/openvic-extension/classes/GFXSpriteTexture.hpp, extension/src/openvic-extension/singletons/AssetManager.hpp, extension/src/openvic-extension/singletons/GameSingleton.cpp, extension/src/openvic-extension/singletons/GameSingleton.hpp, extension/src/openvic-extension/singletons/PopulationMenu.cpp, extension/src/openvic-extension/utility/UITools.hpp, extension/src/openvic-extension/utility/Utilities.hpp
Update the SIM submodule 3 times, each including corresponding changes to this repo:
- SIM adds `GFX::Actor` and renames `GFX.hpp` to `GFXSprite.hpp` which requires include path changes in this repo.
- SIM changes map pixel position to province/index functions, requiring uses of those functions to be changed in this repo and the addition of `GameSingleton::get_map_dims` and `Utilities::from_godot_ivec2`.
- SIM adds support for getting the total population of a region, which is then displayed in the population menu.
=> Update SIM submodule

extension/src/openvic-extension/classes/GFXPieChartTexture.hpp, extension/src/openvic-extension/classes/MapMesh.cpp, extension/src/openvic-extension/singletons/GameSingleton.cpp, extension/src/openvic-extension/singletons/LoadLocalisation.cpp, extension/src/openvic-extension/singletons/MenuSingleton.cpp, extension/src/openvic-extension/singletons/PopulationMenu.cpp, extension/src/openvic-extension/utility/Utilities.cpp
- Reduces unnecessary re-allocations and copies by resizing `godot::Array`s before filling them and `std::move`-ing `godot::Array`s and `godot::Dictionary`s.
- Check return value of resize calls.
=> Pre-allocate and use std::move for Godot Arrays and Dictionaries

extension/src/openvic-extension/singletons/AssetManager.cpp, extension/src/openvic-extension/singletons/AssetManager.hpp, extension/src/openvic-extension/singletons/GameSingleton.cpp, extension/src/openvic-extension/utility/UITools.cpp
- Switch `AssetManager` to use a bitfield argument to set load flags, rather than a bool argument per flag.
- Improve asset caching, storing a `nullptr` on failed loads in case of future attempts to load the same asset, and allowing image and texture caching to be controlled separately to avoid needlessly storing large images that are only needed as (GPU) textures.
=> Add AssetManager LoadFlags

extension/src/openvic-extension/classes/GFXMaskedFlagTexture.cpp, extension/src/openvic-extension/classes/GFXMaskedFlagTexture.hpp, extension/src/openvic-extension/singletons/GameSingleton.cpp, extension/src/openvic-extension/singletons/GameSingleton.hpp
Flags are now loaded into a single large image/texture, rather than being stored as individual images.
`GFXMaskedFlagTexture` accesses flags through rects marking regions of the sheet.
3D flag models will use the texture form of the sheet, with an index passed to a shader indicating the specific flag to extract.
=> Switch to using a single flag sheet image/texture

extension/src/openvic-extension/singletons/GameSingleton.cpp, extension/src/openvic-extension/singletons/GameSingleton.hpp, game/src/Game/GameSession/MapText.gd, game/src/Game/GameSession/MapView.gd, game/src/Game/GameSession/MapView.tscn
There are now 3 zoom states:
- closest ("detailed") - terrain map used, province names visible (and models soon too)
- middle - terrain map used but without province names
- farthest ("parchment") - parchment map used, no province names
=> Add province names and improve zooming

extension/src/openvic-extension/classes/GUINode.cpp, extension/src/openvic-extension/classes/GUINode.hpp, game/src/Game/GameSession/GameSession.tscn, game/src/Game/GameSession/GameSessionMenu.tscn, game/src/Game/GameSession/MapControlPanel/MapControlPanel.tscn, game/src/Game/GameSession/MapView.gd, game/src/Game/GameSession/ProvinceOverviewPanel.gd, game/src/Game/GameSession/Topbar.gd, game/src/Game/Menu/SaveLoadMenu/SaveLoadMenu.tscn, game/src/Game/MusicConductor/MusicPlayer.tscn
Fixes #201 
Minimizes panel mouse obstruction to scripted panel images (functionally what is currently visible)
Prevents map view from hovering inside UI elements
Unsets province hover when not over provinces
---
Add `GUINode.click_mask`
* Prevents mouse interactions not within click_mask
Add `GUINode.set_click_mask_from_nodepaths`
* Generates click_mask from paths relating to GUINode textures
* Sets nodepaths to MOUSE_FILTER_IGNORE
Add CanvasLayer parent to GameSession UI nodes
Set mouse_force_pass_scroll_events to GameSession UI nodes
Set MapControlPanel mouse_filter to default (MOUSE_FILTER_STOP)
Move MapView mouse viewport changes to _input
Move MapView _action_drag released check to _input
Move MapView processing to _process
Remove viewport and window notifications
Disable if window …
=> Improve map view and game panel user experience

extension/src/openvic-extension/classes/GUINode.cpp, extension/src/openvic-extension/classes/GUINode.hpp, extension/src/openvic-extension/singletons/PopulationMenu.cpp, extension/src/openvic-extension/utility/Utilities.cpp, extension/src/openvic-extension/utility/Utilities.hpp, game/src/Game/GameSession/NationManagementScreen/PopulationMenu.gd, game/src/Game/GameSession/ProvinceOverviewPanel.gd, game/src/Game/GameSession/Topbar.gd
- Updates int/float to string formatting functions, in particular adding a suffix-based float formatting function as well as renaming the existing decimal place formatting function.
- Adds control code for rebel icons in the population menu, with regular rebel factions fully wired up to the simulation. Social/political movement rebels and national/flag-associated rebels still need more sim code before we can wire up their icons.
- Cleaned up population menu table sorting functions by adding some helper templates.
- Wire up all Topbar nodes at the GDScript level, using placeholder data but still with all the correct formatting functions to make the switch to actual data as easy as possible. The only unfinished bits are non-uniform label colouring (i.e. different colours in the same label), …
=> Topbar display data + Population menu rebel icons

game/src/Game/GameSession/MapControlPanel/Minimap.gd, game/src/Game/GameSession/MapView.gd
Add MapView queue_province_hover_update
Fix edge scrolling continuing when mouse leaves window
Add province hover reset when mouse leaves the window
Change _edge_move_threshold to 0.025
=> Fix Minimap click doing nothing

.github/workflows/builds.yml
- Update OpenVic-Simulation and scripts to propagate fixes for SCons 4.8.0 (backwards compatible with 4.7.0)
- Force this repository's build actions to use SCons 4.7.0 rather than the most recent version as godot-cpp for Godot 4.2.2 doesn't work with 4.8.0. We should be able to remove this requirement with Godot 4.3's godot-cpp, bringing this repository back in line with the others which already use 4.8.0 (OpenVic-Simulation, OpenVic-Dataloader, lexy-vdf).
=> Update/Fix for SCons 4.8.0

game/src/Game/Model/UnitModel.gd, game/src/Game/Model/XACLoader.gd, game/src/Game/Model/flag.gdshader, game/src/Game/Model/scrolling.gdshader, game/src/Game/Model/scrolling_mat.tres, game/src/Game/Model/unit_colours.gdshader, game/src/Game/Model/unit_colours_mat.tres
Tested for all vanilla models with scrolling textures. Examples can be seen by adding the following to a starting units OOB text file (and changing [the default unit animation](https://github.com/OpenVicProject/OpenVic/blob/master/game/src/Game/GameSession/ModelManager.gd#L56) to `MOVE` or `ATTACK`):
```
army = {
name = "TANK TEST"
location = 292
regiment = {
name = "Tank"
type = tank
home = 300
}
}
navy = {
name = "STEAM TEST"
location = 2732
ship = {
name = "Steam Transport"
type = steam_transport
}
}
```
=> Scrolling model materials (tank tracks and smoke)

game/src/Game/GameSession/MapView.gd
Fixes #248 
Remove _cardinal_movement_vector function in favor of variable
Move map movement handling to _unhandled_input
=> Add movement prevention if any gui has focus

extension/src/openvic-extension/classes/GFXMaskedFlagTexture.cpp, extension/src/openvic-extension/classes/GFXPieChartTexture.cpp, extension/src/openvic-extension/classes/GFXPieChartTexture.hpp, extension/src/openvic-extension/classes/GFXSpriteTexture.cpp, extension/src/openvic-extension/classes/GUIListBox.cpp, extension/src/openvic-extension/classes/GUIOverlappingElementsBox.cpp, extension/src/openvic-extension/classes/GUIScrollbar.cpp, extension/src/openvic-extension/singletons/AssetManager.cpp, extension/src/openvic-extension/singletons/GameSingleton.cpp, extension/src/openvic-extension/singletons/LoadLocalisation.cpp, extension/src/openvic-extension/singletons/MenuSingleton.cpp, extension/src/openvic-extension/singletons/ModelSingleton.cpp, extension/src/openvic-extension/singletons/PopulationMenu.cpp, extension/src/openvic-extension/utility/UITools.cpp, extension/src/openvic-extension/utility/Utilities.cpp, extension/src/openvic-extension/utility/Utilities.hpp, game/src/Game/GameSession/ProvinceOverviewPanel.gd, game/src/Game/GameSession/SearchPanel.gd
Fixes #180: Province names do not convert non-ascii characters to Unicode
=> Use UTF8 encoding and simplify godot string conversion

docs/simulation/calculations.yaml
The Second Appearance — Today at 14:49
Also try setting FOR and PER regiment to 3000 - you will be able to recruit 2 brigades from a single 3000 pop, but each 3k further will only provide 1 brigade
General WVPM — Today at 15:01
Weird. When POP_MIN_SIZE_FOR_REGIMENT = 4500 & POP_SIZE_PER_REGIMENT = 5000 a pop with 4500 can support max 1 regiment.
When POP_MIN_SIZE_FOR_REGIMENT = 5000 & POP_SIZE_PER_REGIMENT = 5000 a pop with 5000 can support max 2 regiments.
So maybe instead of ceil() it should be 1 + trunc().
=> Correct Maximum regiments per soldier POP

docs/simulation/calculations.yaml
"About sum_workforce_in_state, workforce is the term used in the files to define the amount of jobs a production type offers.
Note only factory jobs are counted in Victoria 2."
https://discord.com/channels/1063392556160909312/1105422811809452072/1283084994620821544
=> Rename sum_workforce_in_state to total_factory_jobs_in_state

extension/src/openvic-extension/singletons/SoundSingleton.cpp, game/src/Game/MusicConductor/MusicConductor.gd
Adds a null check in music loading and removes an unnecessary import in soundsingleton.cpp.
=> music null check

game/src/Game/Model/XACLoader.gd, game/src/Game/Model/XSMLoader.gd
Fixes the following problems:
- Arab_infantry_helmet
- Parts of units being culled when near edge of screen (added cull margin)
- Improper method of determining when to use int16 or float32 quaternions for xsm animations.
Background of Arab_infantry_helmet
Paradox made the helmet models directly on the infantry units they go with. These helmet models are properly separated to their own .xac files so they are normally reuseable attachments. However, the mesh for the arab_infantry_helmet was never removed from the infantry model, so it was appearing twice. So a check was made so that we skip building the helmet's mesh if it is in a file with other mesh chunks (ie. the infantry model)
New method of determining whether to use int16 or float32 for xsm quaternions is to check the chunk version, …
=> Model loader Fixes

docs/simulation/calculations.yaml
=> Document rgo production

docs/contribution/system-requirements.md
- GCC 12 for Ubuntu 22.04 needs to be manually installed and set as the primary g++ tool
- Updated System Requirements documentation to add the additional system commands
=> Updated System Requirements For Ubuntu 22.04

.github/dependabot.yml
Adds config for GitHub Dependabot to automatically raise PRs to bump submodule versions.
=> Use Dependabot to Automatically Update Dependencies

extension/src/openvic-extension/classes/GUIHasTooltip.hpp, game/src/Game/GameSession/NationManagementScreen/PopulationMenu.gd, game/src/Game/GameSession/Topbar.gd
Since we now no longer have to change the mouse filter of nodes with tooltips but default mouse filter IGNORE manually, I have removed that code for the following nodes:
- Topbar
- Total rank label
- Prestige label
- Prestige rank label
- Industrial power label
- Industrial power rank label
- Military power label
- Military power rank label
- Colonial power label
- Current research label
- National literacy label
- Research points label
- Army size label
- Navy size label (tooltip not yet implemented)
- Mobilisation size label
- Leadership points label (tooltip not yet implemented)
- Population Menu
- Culture labels
- Religion icons
- Localtion labels
- Militancy labels
- Consciousness labels
- Cash labels
- Size change icons
- Literacy labels
- Distribution legend colour icons
=> When setting a tooltip, automatically switch mouse filter to PASS if it's IGNORE

extension/src/openvic-extension/classes/GUILabel.cpp, extension/src/openvic-extension/singletons/MenuSingleton.cpp, game/src/Game/GameSession/ProvinceOverviewPanel.gd
This adds the tooltip to the rgo_employment_population_label. The other ones have a test message. I am having some trouble with accessing the modifier_effect_cache since there is no getter for it unless there is a different place where that information is stored.
=> Add tooltip for RGO_employment

.github/workflows/builds.yml, README.md
Add Extension Class Reference Documentation instructions to README.md
Fix .github changes not triggering workflow
=> Add class reference checks to Github builds workflow

extension/src/openvic-extension/classes/GUINode.cpp
Prevents high opacity panel shadows eating mouse interactions
=> Fix GUINode click mask low alpha threshold

extension/doc_classes/MapItemSingleton.xml, extension/src/openvic-extension/classes/GUILabel.cpp, extension/src/openvic-extension/classes/GUIOverlappingElementsBox.cpp, extension/src/openvic-extension/register_types.cpp, extension/src/openvic-extension/singletons/MapItemSingleton.cpp, extension/src/openvic-extension/singletons/MapItemSingleton.hpp, game/src/Game/GameSession/BillboardManager.gd, game/src/Game/GameSession/GameSession.tscn, game/src/Game/GameSession/billboard.gdshader
Billboards are used for various mapmodes, and for displaying nation capitals on the map.
Bunch of TODOS:
- Move billboards to own viewport so they don't clip into unit models or occlude them
- hide billboards when zoomed out
- Make billboards correspond to the map mode
- Stop capital billboards and map mode billboards from occluding eachother
- Fix billboard lighting
- Get billboards to display in the proper order if possible (occasionally a billboard will display behind another one which is further back)
=> Add Map Billboards

extension/doc_classes/MapItemSingleton.xml, extension/src/openvic-extension/singletons/MapItemSingleton.cpp, extension/src/openvic-extension/singletons/MapItemSingleton.hpp, game/src/Game/GameSession/BillboardManager.gd, game/src/Game/GameSession/billboard.gdshader
- Province icons (RGOs, crimes, national foci) are now scaled by 0.75 vertically, while capitals are still 1:1.
- Some tweaks to billboard management:
- we only set up billboards we actually use, the others are ignored.
- `StringName`s are used over `String`s where possible.
- `ProvinceBillboards` enum values are used where possible rather than hardcoded strings.
=> Fix province icon scaling

game/src/Game/Model/XACLoader.gd
Presently the `polysurface97` exclusion on the XAC loader, added to stop extra arab infantry helmets, also stops the Sardinia-Piedmont infantry from loading. This fix adds the condition that `polysurface97` must have no bone weighting to be excluded.
=> fix sp infantry

extension/doc_classes/CursorSingleton.xml, extension/src/openvic-extension/register_types.cpp, extension/src/openvic-extension/singletons/CursorSingleton.cpp, extension/src/openvic-extension/singletons/CursorSingleton.hpp, extension/src/openvic-extension/singletons/SoundSingleton.cpp, extension/src/openvic-extension/utility/Utilities.hpp, game/project.godot, game/src/Game/Autoload/CursorManager.gd, game/src/Game/GameSession/GameSession.gd, game/src/Game/GameSession/GameSessionMenu.gd, game/src/Game/GameStart.gd, game/src/Game/LoadingScreen.tscn
Draft, loads cursors, animated and not animated, handles switching between cursors.
Currently contains code just for testing/demoing: right click the mouse to cycle through loaded cursors. The watch is set as an i-beam cursor so that you can try hovering over a text field (ex. in the new-game menu) to observe how the Cursor Manager handles auto-switching between animated cursors.
Loading of the cursors and generating new resolutions handled by the c++ side CursorSingleton. Managing what frame to display, and when to switch cursors handled by gdscript side CursorManager. This architecture is because we want a c++ dataloader, but we also need to listen to the scene tree to know when its safe to call a hardware cursor change.
Possible improvements:
- Doesn't support the full image spec …
=> Add cursor support

extension/doc_classes/GUILineChart.xml, extension/src/openvic-extension/classes/GUILineChart.cpp
Fixes GUILineChart preventing the mouse from passing to Controls underneath.
=> Set GUILineChart's mouse_filter to ignore

game/src/Game/GameMenu.tscn, game/src/Game/GameSession/GameSession.gd, game/src/Game/GameSession/GameSession.tscn, game/src/Game/GameSession/MapView.gd, game/src/Game/Menu/LobbyMenu/LobbyMenu.gd, game/src/Game/Menu/LobbyMenu/LobbyMenu.tscn
Replace MapView province hover behavior with signal
Replace MapView province unhover behavior with signal
Replace MapView province click behavior with signal
Replace MapView province right click behavior with signal
Add MapView province behavior signal implementations to GameSession
Add LobbyMenu MapView TODOs
Change GameSession scene type to Node
=> Add MapView to LobbyMenu

game/assets/localisation/locales/en_GB/menus.csv, game/project.godot, game/src/Game/Autoload/Events.gd, game/src/Game/Autoload/Events/Multiplayer.gd, game/src/Game/GameMenu.gd, game/src/Game/GameMenu.tscn, game/src/Game/Menu/LobbyMenu/LobbyMenu.gd, game/src/Game/Menu/MainMenu/MainMenu.gd, game/src/Game/Menu/MultiplayerMenu/ConnectionFailDialog.gd, game/src/Game/Menu/MultiplayerMenu/DirectConnectionEntry.gd, game/src/Game/Menu/MultiplayerMenu/DirectConnectionEntry.tscn, game/src/Game/Menu/MultiplayerMenu/DirectConnectionTab.gd, game/src/Game/Menu/MultiplayerMenu/DirectConnectionTab.tscn, game/src/Game/Menu/MultiplayerMenu/HostTab.gd, game/src/Game/Menu/MultiplayerMenu/HostTab.tscn, game/src/Game/Menu/MultiplayerMenu/MultiplayerMenu.gd, game/src/Game/Menu/MultiplayerMenu/MultiplayerMenu.tscn, game/src/Game/Menu/MultiplayerMenu/PasswordDialog.gd, game/src/Game/Menu/MultiplayerMenu/SecretEdit.gd, game/src/Game/Menu/MultiplayerMenu/SecretEdit.tscn, game/src/Game/Menu/SaveLoadMenu/SaveLoadMenu.gd
Adds an initial MP menu consisting of a direct connection tab and a host tab.
- Entries made in the direct connection tab are saved in plain text to a config file ips.cfg (this could change if we add accounts).
- When the player clicks to join a game, the entered IP is validated, a password entry prompt is shown, and a dummy error popup is shown. 
- No actual networking functionality. There are a couple functions defined which for now print the player name, password, and entered ip where this should be added later.
=> Add multiplayer menu

game/src/Game/GameSession/NationManagementScreen/PoliticsMenu.gd
Added all the basic GUI variables and got them piped from the .gui file. Also includes placeholder functions for all added buttons.
Note:
This does not include more complex listbox/panel entries such as
-Ideology Option
-Issue Option
-Reform Option
-Decision Entry
-Rebel Entry
-Party Window
-Select New Party
-Party Issue Option
-Release Nation Entry
-Movement Entry
I didn't know how to handle these, some of these may be better served being sub classes, especially those that are listbox entries.
Also didn't have time to test building it so if it breaks, oops
=> Basic GUI Variables set up and piped for Politics Menu

.vscode/launch.json, extension/doc_classes/StyleBoxWithSound.xml, extension/src/openvic-extension/classes/resources/StyleBoxWithSound.cpp, extension/src/openvic-extension/classes/resources/StyleBoxWithSound.hpp, extension/src/openvic-extension/singletons/SoundSingleton.cpp, extension/src/openvic-extension/singletons/SoundSingleton.hpp, extension/src/openvic-extension/utility/UITools.cpp
Fix StyleBoxWithSound draw bug
Expose SoundSingleton audio stream load functions
Update OpenVicProject/OpenVic-Simulation@34d3227224114e1c6ae56aeaab2550a14e5dff41
=> Add clicksound support to Buttons

extension/doc_classes/MapItemSingleton.xml, extension/src/openvic-extension/singletons/AssetManager.cpp, extension/src/openvic-extension/singletons/MapItemSingleton.cpp, extension/src/openvic-extension/singletons/MapItemSingleton.hpp, game/project.godot, game/src/Game/GameSession/BillboardManager.gd, game/src/Game/GameSession/MapView.gd, game/src/Game/GameSession/MapView.tscn, game/src/Game/GameSession/Projection.gdshader, game/src/Game/GameSession/ProjectionManager.gd, game/src/Game/GameSession/SelectionMarkers.gd, game/src/Game/GameSession/ValidMoveMarkers.gd
Adds support for the unit selection and valid/invalid move markers (which in vic2 are ProjectionType).
- To see the selection markers: shift+left-click to add a marker at a unit position. left-click to clear the projections.
- Right click on provinces to add valid/invalid movement markers.
A main limitation is that the selection markers do not follow units, but are placed wherever a province is shift+clicked. This won't be fixeable until we have proper unit selection
=> Add map projections

extension/doc_classes/GameSingleton.xml, extension/doc_classes/MenuSingleton.xml, extension/doc_classes/PlayerSingleton.xml, extension/src/openvic-extension/singletons/GameSingleton.cpp, extension/src/openvic-extension/singletons/GameSingleton.hpp, extension/src/openvic-extension/singletons/MenuSingleton.cpp, extension/src/openvic-extension/singletons/MenuSingleton.hpp, extension/src/openvic-extension/singletons/PlayerSingleton.cpp, extension/src/openvic-extension/singletons/PlayerSingleton.hpp, game/src/Game/GameSession/NationManagementScreen/MilitaryMenu.gd, game/src/Game/GameSession/NationManagementScreen/TradeMenu.gd, game/src/Game/GameSession/ProvinceOverviewPanel.gd, game/src/Game/GameSession/Topbar.gd
Will come out of draft once [OpenVic-Simulation#296](https://github.com/OpenVicProject/OpenVic-Simulation/pull/296) is merged
=> Make PlayerSingleton manage game actions via new SIM action queue system

extension/src/openvic-extension/classes/GFXPieChartTexture.cpp, extension/src/openvic-extension/classes/GFXPieChartTexture.hpp, extension/src/openvic-extension/classes/GUIPieChart.cpp, extension/src/openvic-extension/singletons/MenuSingleton.cpp, extension/src/openvic-extension/singletons/MenuSingleton.hpp, extension/src/openvic-extension/singletons/PopulationMenu.cpp, game/src/Game/GameSession/NationManagementScreen/PopulationMenu.gd
Relies on `IndexedMap` fix from [OpenVic-Simulation#339](https://github.com/OpenVicProject/OpenVic-Simulation/pull/339)
Fixes a bug with Population Menu where ideology, issue and vote distributions for all currently selected pops (based on selected states/provinces and pop type filters) had mis-scaling and overflow issues due to each pop's contribution being multiplied by its size despite the pop's ideology/issue/vote distribution already being scaled so that it's total weight equals its size.
=> Allow pie chart tooltip customisation and fix Population Menu over-scaling

SConstruct
Godot relies on dynamic_casts, extensions require RTTI
This is waiting for scripts dependency to be updated.
=> Ensure rtti is always enabled

.github/workflows/builds.yml
Fixes the occasional failure caused by considering the godot.project file erroneously for the class reference check.
=> Narrow the scope of class reference checks to xml files

extension/doc_classes/MenuSingleton.xml, extension/src/openvic-extension/classes/BudgetComponent.cpp, extension/src/openvic-extension/classes/BudgetComponent.hpp, extension/src/openvic-extension/components/budget/AdministrationBudget.cpp, extension/src/openvic-extension/components/budget/AdministrationBudget.hpp, extension/src/openvic-extension/components/budget/BudgetMenu.cpp, extension/src/openvic-extension/components/budget/BudgetMenu.hpp, extension/src/openvic-extension/components/budget/EducationBudget.cpp, extension/src/openvic-extension/components/budget/EducationBudget.hpp, extension/src/openvic-extension/components/budget/MilitaryBudget.cpp, extension/src/openvic-extension/components/budget/MilitaryBudget.hpp, extension/src/openvic-extension/components/budget/NationalStockpileBudget.cpp, extension/src/openvic-extension/components/budget/NationalStockpileBudget.hpp, extension/src/openvic-extension/components/budget/SocialBudget.cpp, extension/src/openvic-extension/components/budget/SocialBudget.hpp, extension/src/openvic-extension/components/budget/StrataTaxBudget.cpp, extension/src/openvic-extension/components/budget/StrataTaxBudget.hpp, extension/src/openvic-extension/components/budget/TariffBudget.cpp, extension/src/openvic-extension/components/budget/TariffBudget.hpp, extension/src/openvic-extension/singletons/GameSingleton.cpp, extension/src/openvic-extension/singletons/GameSingleton.hpp, extension/src/openvic-extension/singletons/MenuSingleton.cpp, extension/src/openvic-extension/singletons/MenuSingleton.hpp, extension/src/openvic-extension/singletons/PlayerSingleton.cpp, extension/src/openvic-extension/singletons/PlayerSingleton.hpp, extension/src/openvic-extension/utility/Utilities.cpp, extension/src/openvic-extension/utility/Utilities.hpp, game/src/UI/Session/BudgetMenu.gd
- Depends #507 
Splits up the budget menu into components.
Each component manages it's own slider and label.
When the balance of a component changes, it emits a c++ signal so the budget menu can update.
This PR moves a lot of UI code from godot to c++.
=> Reactive budget menu

extension/src/openvic-extension/classes/GFXMaskedFlagTexture.cpp, extension/src/openvic-extension/classes/GFXPieChartTexture.cpp, extension/src/openvic-extension/classes/GFXSpriteTexture.cpp, extension/src/openvic-extension/classes/GUILineChart.cpp, extension/src/openvic-extension/classes/GUINode.cpp, extension/src/openvic-extension/classes/GUIOverlappingElementsBox.cpp, extension/src/openvic-extension/classes/GUIScrollbar.cpp, extension/src/openvic-extension/components/budget/AdministrationBudget.cpp, extension/src/openvic-extension/components/budget/BudgetMenu.cpp, extension/src/openvic-extension/components/budget/DiplomaticBudget.cpp, extension/src/openvic-extension/components/budget/EducationBudget.cpp, extension/src/openvic-extension/components/budget/MilitaryBudget.cpp, extension/src/openvic-extension/components/budget/SocialBudget.cpp, extension/src/openvic-extension/components/budget/StrataTaxBudget.cpp, extension/src/openvic-extension/components/budget/abstract/SliderBudgetComponent.cpp, extension/src/openvic-extension/singletons/AssetManager.cpp, extension/src/openvic-extension/singletons/CursorSingleton.cpp, extension/src/openvic-extension/singletons/GameSingleton.cpp, extension/src/openvic-extension/singletons/LoadLocalisation.cpp, extension/src/openvic-extension/singletons/MapItemSingleton.cpp, extension/src/openvic-extension/singletons/MenuSingleton.cpp, extension/src/openvic-extension/singletons/MilitaryMenu.cpp, extension/src/openvic-extension/singletons/ModelSingleton.cpp, extension/src/openvic-extension/singletons/PopulationMenu.cpp, extension/src/openvic-extension/singletons/SoundSingleton.cpp, extension/src/openvic-extension/singletons/TradeMenu.cpp, extension/src/openvic-extension/utility/UITools.cpp, extension/src/openvic-extension/utility/Utilities.cpp, extension/src/openvic-extension/utility/Utilities.hpp
the godot engine has a cpp implementation that emulates the godot script features. One commonly used feature is string formatting. In godot script you can just use `%`. In godot-cpp you use `godot::vformat(template, ...)`.
The issue is this is implemented as follows:
```cpp
template <typename... VarArgs>
String vformat(const String &p_text, const VarArgs... p_args) {
Variant args[sizeof...(p_args) + 1] = { p_args..., Variant() }; // +1 makes sure zero sized arrays are also supported.
Array args_array;
args_array.resize(sizeof...(p_args));
for (uint32_t i = 0; i < sizeof...(p_args); i++) {
args_array[i] = args[i];
}
return p_text % args_array;
}
```
So it creates a new array each invocation.
The array is always discarded afterwards, resulting in redundant allocations and deallocations. …
=> Optimise godot::vformat by pooling args array

extension/src/openvic-extension/components/budget/BudgetMenu.cpp, extension/src/openvic-extension/components/budget/BudgetMenu.hpp, extension/src/openvic-extension/components/budget/StrataTaxBudget.cpp
This fixes the errors of unreferenced static string for strata names, eliminating the only errors in running OpenVic currently, neither StringNames nor Strings have a constructor that takes a length, when length was being called on StringNames it was just setting the static bool to true (unless it was empty) because of the implicit conversion of size_t to bool. StringName construction here also didn't make any sense anyway, it costed useless performance for no gain because it was then construction a StringName from a String that was was made from a StringName, and in other cases the construction of a StringName was completely useless because it was never consumed as a StringName.
=> Replace useless StringName construction with String
